/**
 * next/image loader for the static export (STATIC_EXPORT=true).
 * Maps an image request to a WebP variant pre-generated by
 * scripts/build-static.mjs at /_img/<name>-<width>.webp.
 */
export const IMAGE_WIDTHS = [640, 960, 1280, 1920, 2400] as const;

export default function staticImageLoader({ src, width }: { src: string; width: number; quality?: number }) {
  if (!src.startsWith("/images/")) return src;
  const chosen = IMAGE_WIDTHS.find((w) => w >= width) ?? IMAGE_WIDTHS[IMAGE_WIDTHS.length - 1];
  const name = src
    .replace(/^\/images\//, "")
    .replace(/\.[a-z0-9]+$/i, "")
    .replace(/\//g, "__");
  return `/_img/${name}-${chosen}.webp`;
}
