import Image from "next/image";
import { MapPin } from "@phosphor-icons/react/dist/ssr";
import { heroMaps, type HeroMapVariant } from "@/content/hero-map";
import { cn } from "@/lib/cn";

/** Label position relative to each pin's tip; Nepal's label flips left on the narrow crop to stay in frame. */
const labelPlacement: Record<HeroMapVariant, Record<string, string>> = {
  wide: {
    london: "translate-x-5 -translate-y-[2.6rem]",
    nepal: "-translate-x-[calc(100%+1.25rem)] -translate-y-[2.6rem]",
  },
  corridor: {
    london: "translate-x-4 -translate-y-[2.1rem]",
    nepal: "-translate-x-[calc(100%+1rem)] -translate-y-[2.1rem]",
  },
};

/**
 * Flat dotted map of the UK-to-Nepal corridor (generated by
 * scripts/generate-hero-map.mjs) with drop pins on London and Nepal. Rendered on the
 * server; the pins drop in with CSS only and stay still under reduced motion.
 */
export function HeroMap({
  variant,
  tone = "dark",
  priority = true,
  className,
}: {
  variant: HeroMapVariant;
  tone?: "dark" | "light";
  /** Load eagerly; turn off when the map is not in the first viewport. */
  priority?: boolean;
  className?: string;
}) {
  const { src: darkSrc, width: W, height: H, pins } = heroMaps[variant];
  const src = tone === "light" ? darkSrc.replace(".svg", "-light.svg") : darkSrc;
  const light = tone === "light";
  const size = variant === "wide" ? "size-9" : "size-7";

  return (
    <figure
      className={cn("relative w-full", className)}
      style={{ aspectRatio: `${W} / ${H}` }}
      aria-label="Map showing Ample Associates in London and Nepal"
    >
      <Image src={src} alt="" fill priority={priority} sizes="100vw" className="select-none" />
      {pins.map((p, i) => (
        <div
          key={p.id}
          aria-hidden
          className="absolute"
          style={{ left: `${(p.x / W) * 100}%`, top: `${(p.y / H) * 100}%` }}
        >
          {/* Ground shadow under the pin tip */}
          <span
            className={cn(
              "absolute h-1.5 w-4 -translate-x-1/2 -translate-y-1/2 rounded-full blur-[2px]",
              light ? "bg-navy-950/25" : "bg-black/50",
            )}
          />
          <span className="absolute -translate-x-1/2 -translate-y-full">
            <span className="map-pin block" style={{ animationDelay: `${200 + i * 180}ms` }}>
              <MapPin
                weight="fill"
                className={cn(
                  size,
                  light
                    ? "text-brand-600 drop-shadow-[0_6px_10px_rgb(61_3_250/0.35)]"
                    : "text-sky-400 drop-shadow-[0_4px_6px_rgb(0_0_0/0.45)]",
                )}
              />
            </span>
          </span>
          <span
            className={cn(
              "absolute rounded-full px-3 py-1 text-[0.6875rem] font-semibold tracking-[0.12em] whitespace-nowrap uppercase backdrop-blur-md",
              light ? "bg-white/85 text-ink shadow-lift" : "border border-white/15 bg-navy-950/85 text-white",
              labelPlacement[variant][p.id],
            )}
          >
            {p.city}
          </span>
        </div>
      ))}
    </figure>
  );
}
