// Generated by scripts/generate-hero-map.mjs. Do not edit by hand.
export const heroMaps = {
  wide: {
    src: "/maps/wide.svg",
    width: 187.5,
    height: 72.88,
    pins: [
      {
        id: "london",
        city: "London",
        country: "United Kingdom",
        x: 95.5,
        y: 20.78,
      },
      {
        id: "nepal",
        city: "Nepal",
        country: "Nepal",
        x: 169,
        y: 47.63,
      },
    ],
  },
  corridor: {
    src: "/maps/corridor.svg",
    width: 104.5,
    height: 70.28,
    pins: [
      {
        id: "london",
        city: "London",
        country: "United Kingdom",
        x: 13,
        y: 18.19,
      },
      {
        id: "nepal",
        city: "Nepal",
        country: "Nepal",
        x: 91,
        y: 45.9,
      },
    ],
  },
} as const;

export type HeroMapVariant = keyof typeof heroMaps;
